application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_username: "user@name.com"
  authorization_password: "secret"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
